### ISSUE TITLE
Simple benchmarking Problem

### ISSUE THREAD

**Issue by QiZhou1512** [owensgroup/SlabHash#7]
After the code has been compiled successfully, I tried to run the simple benchmark **python3 ../bench/bencher.py -m 1 -d 0** but it gives me this error:

python3 ../bench/bencher.py -m 0 -d 0
intermediate results stored at: ../build/bench_result/out_2019-06-21_10:12:53.438823.json
mode = 0
 === Started benchmarking ... 
 === Done!
Traceback (most recent call last):
  File "../bench/bencher.py", line 230, in <module>
    main(sys.argv[1:])					
  File "../bench/bencher.py", line 218, in main
    analyze_singleton_experiment(input_file)
  File "../bench/bencher.py", line 9, in analyze_singleton_experiment
    with open(input_file) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '../build/bench_result/out_2019-06-21_10:12:53.438823.json'

**Comment by sashkiani** [comment]
What GPU architecture do you have?
